### ISSUE TITLE
[Bug] Autosize Token with Token Actor Sheets

### ISSUE THREAD

**Issue by Havoclivekiller** [moo-man/WFRP4e-FoundryVTT#650] opened 2021-06-12 16:41 UTC
Token Actor Sheets seem to bug out with their autosize based on the Size trait. Making a token actor sheet for example from a Zombie to a Zombie Child (with the Size (Small) trait) will bug out if you copy paste it (normal Zombies will change size) or add a new Zombie (Zombie Child tokens will revert to normal size).

**Comment by moo-man** [comment] 2021-06-12 16:42
I'm going to close this as 0.8 changes a lot regarding this area and the issue is likely not relevant

**Closed by moo-man** 2021-06-12 16:42 UTC
