### ISSUE TITLE
[WFRP4e System] Encumbrance effects are no longer applied when overencumbered

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1781] opened 2023-09-24 18:59 UTC
To reproduce: 
- Add trappings to an actor until they become Encumbered.
- The Encumbrance 1 effect is no longer instantly added to Temporary Effects.<br/>**From**: thefirst5<br/>foundry: 11.308<br/>wfrp4e: 7.0.2<br/>wfrp4e-altdorf: 4.0.1<br/>wfrp4e-archives1: 4.0.1<br/>wfrp4e-archives2: 4.0.1<br/>wfrp4e-core: 4.0.1<br/>wfrp4e-dotr: 4.0.1<br/>wfrp4e-eis: 4.0.1<br/>wfrp4e-horned-rat: 4.0.1<br/>wfrp4e-middenheim: 4.0.1<br/>wfrp4e-pbtt: 4.0.1<br/>wfrp4e-rnhd: 4.0.1<br/>wfrp4e-up-in-arms: 4.0.1<br/>wfrp4e-wom: 4.0.1<br/>Active Modules: about-face, dd-import, drag-ruler, easy-target, fast-flip, forien-armoury, foundryvtt-simple-calendar, fxmaster, lib-wrapper, popout, quick-insert, smalltime, socketlib, stairways, times-up, token-action-hud-core, token-action-hud-wfrp4e, token-z, wfrp4e-gm-toolkit, forge-vtt

**Comment by TheFirst05** [comment] 2023-10-16 21:19
For what it's worth, I've dug deeper, and the steps to reproduce are more complicated:

Have an actor that is assigned to a user with player permissions
Log in as GM **and** log in as the player
While the GM and player are both connected, the actor sheet does not create/delete the encumbrance effect
If the player logs out, the actor sheet works as intended.

No errors in the console log. Tested on a newly created actor.

**Closed** 2023-10-19 05:35 UTC
Labels: system, bug
