### ISSUE TITLE
the number of successes on the check does not match to the number of the CN creation (when the spell is not remembered)

### ISSUE THREAD

**Issue by Grinpis300** [moo-man/WFRP4e-FoundryVTT#1732] opened 2023-08-12 18:41 UTC
Из : Grinpis#9194
Foundry: 11.307
wfrp4e: 6.6.1
wfrp4e-core: 3.1.6
Активные модули: babele, dice-calculato
![Безымянный](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/136200476/214f4912-d552-41ee-a4a2-60538a134e29)
![1](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/136200476/d14c99f5-ef10-48c5-889b-2ed3a034f4e2)
![260252054-66ccd527-b30c-4995-9652-d760c59e4081](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/136200476/5a841bfc-c007-422e-bd49-81b3a431f124)
r, dice-so-nice, lib-wrapper, ru-ru, wfrp4e-character-details

**Comment by moo-man** [comment] 2023-08-28 01:25
Seems like a duplicate of #1731

**Closed by moo-man** 2023-08-28 01:25 UTC
Labels: duplicate, system, bug
