### ISSUE TITLE
[WFRP4e System] Transferring an item

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2310] opened 2024-11-22 11:48 UTC
There are several problems when transferring items between 2 actors. 
1) If you transfer an item from actor A's sheet to a container located in Actor B's sheet, the item disappears from sheet A, but does not appear in sheet B. I would like it to be possible to put the item directly into the container.
2) If you try to move a container with objects from actor A's sheet to actor B's sheet, then actor B will have only a container, and all the objects from it will disappear. They will disappear completely from the actor's list.<br/>**From**: mrak_x<br/>foundry: 12.331<br/>wfrp4e: 8.2.2<br/>wfrp4e-altdorf: 6.0.1<br/>wfrp4e-archives1: 6.0.1<br/>wfrp4e-archives2: 6.0.1<br/>wfrp4e-archives3: 6.0.0<br/>wfrp4e-core: 6.0.1<br/>wfrp4e-dotr: 6.0.1<br/>wfrp4e-eis: 6.0.2<br/>wfrp4e-empire-ruins: 6.0.1<br/>wfrp4e-horned-rat: 6.0.1<br/>wfrp4e-middenheim: 6.0.2<br/>wfrp4e-owb1: 6.0.1<br/>wfrp4e-owb2: 6.0.1<br/>wfrp4e-pbtt: 6.0.0<br/>wfrp4e-rnhd: 6.0.2<br/>wfrp4e-salzenmund: 6.0.1<br/>wfrp4e-soc: 6.0.2<br/>wfrp4e-starter-set: 6.0.1<br/>wfrp4e-ua1: 6.0.1<br/>wfrp4e-ua2: 6.0.0<br/>wfrp4e-up-in-arms: 6.0.2<br/>wfrp4e-wom: 6.0.2<br/>wfrp4e-zoo: 6.0.0<br/>Active Modules: about-face, babele, combat-tracker-dock, dice-calculator, easy-ruler-scale, forien-actors-summary, forien-armoury, forien-quest-log, gm-screen, lib-wrapper, ru-ru, ru-wfrp4e, sequencer, socketlib, token-attacher, warhammer-lib, wfrp4e-gm-toolkit

**Comment by Forien** [comment] 2024-11-22 12:00
Are you using Sheet V1 or Sheet V2?

Also it's weird, are you sure no module is interfering? Not only items do not disappear on the "source actor" when you drag them to other Actor, but when you add item to a new actor, it's "location" is scrubbed so they will appear..

**Comment by Mrak7439** [comment] 2024-11-22 12:29
V1.
I have now checked in a world without localization and without modules, only Core. The same thing. You can easily reproduce and see =)

**Comment by Forien** [comment] 2024-11-22 12:36
That's the issue, I cannot reproduce. 

When you drag items they get duplicated, always. And their `location` is scrubbed, so they always appear outside of containers. 

Here is proof of fresh world with no modules (sorry, I lied, there is 1 module, because library is mandatory)

![](https://i.gyazo.com/b5280e53e2a9f8fa414f5b12dad687eb.gif)

**Comment by Mrak7439** [comment] 2024-11-22 17:29
Maybe the auto-translator transmitted the wrong message. Create a container in Sheet A. Put the items in the container in sheet A. After that, drag the container with the items (not the items individually)   in sheet B).

**Comment by Forien** [comment] 2024-11-22 17:31
> Maybe the auto-translator transmitted the wrong message. Create a container in Sheet A. Put the items in the container in sheet A. After that, drag the container with the items (not the items individually) in sheet B).

this will only duplicate container, without its contents. But no items will disappear from the original actor.

**Comment by Mrak7439** [comment] 2024-11-22 17:33
I'm sorry))) I slept all evening, but we figured out that it works. 
Drag the item from Sheet A to the Container located in Sheet B. The item will disappear.

**Comment by Mrak7439** [comment] 2024-11-23 00:11
Yes, being tired definitely doesn't make me clearer. The disappearance of the container with things happens as in the first scenario - when you transfer the container with items in sheet A to sheet B and put it in a container located in sheet B. Most likely this is 1 problem, it turns out, it's just a special case that I dragged the container separately.

**Closed** 2024-12-04 21:47 UTC
Labels: system, bug
